#! /usr/bin/bash
/home/USERNAME/ghcontrol/log_event.sh "Exhaust Fan ON_OFF_TEXT"
/usr/local/bin/EXHAUST_FAN_LEG1_BOARDTYPErelind EXHAUST_FAN_LEG1_BOARDNUMBER write EXHAUST_FAN_LEG1_RELAYNUMBER ON_OFF
/usr/local/bin/EXHAUST_FAN_LEG2_BOARDTYPErelind EXHAUST_FAN_LEG2_BOARDNUMBER write EXHAUST_FAN_LEG2_RELAYNUMBER ON_OFF
