# Basic settings
watchdog-device = /dev/watchdog
log-dir = /var/log/watchdog
logtick = 1
# Time between checks, 10 seconds 
interval = 10
# 10 minutes restart timeout on continuous failure
retry-timeout = 600
# Keep in memory
realtime = yes
# Network monitoring
# Router Address
# ping = 192.168.10.1
# Google Address
ping = 8.8.8.8
# Interface monitoring ( if you have usb wifi, this gets 0 on broadcom wifi and forces restart
#interface = wlan0
